let num1 = prompt("Digite um número:")
num1 = Number(num1)
document.body.innerHTML += `<h2><strong>Seu número é ${num1}</strong></h2> <br />`
document.body.innerHTML += `Raiz quadrada: ${num1 ** 0.5} <br />`
document.body.innerHTML += `${num1} é inteiro: ${Number.isInteger(num1)} <br />`
document.body.innerHTML += `É NaN: ${Number.isNaN(num1)} <br />`
document.body.innerHTML += `Arredondando para baixo: ${Math.floor(num1)} <br />`
document.body.innerHTML += `Arredondando para cima ${Math.ceil(num1)} <br />`
document.body.innerHTML += `Com duas casas decimais: ${num1.toFixed(2)} <br />`